apiVersion: v1
kind: Services
metadata:
  name: maha-svc
  labels: 
    app: myjavaapp
spec: 
  type: NodePort
  ports: 
  - port: 8080
    nodeport: 30001
    protocol: TCP
  selector: 
    app: myjavaapp
   
